FROM --platform=linux/amd64 ubuntu:20.04

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential automake libtool pkg-config bison flex

ADD . /repo
WORKDIR /repo
RUN libtoolize -qi
RUN autoreconf
RUN ./configure
RUN make
