FROM --platform=linux/amd64 ubuntu:20.04 as builder

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential automake libtool pkg-config bison flex

COPY . /repo
WORKDIR /repo
RUN libtoolize -qi
RUN autoreconf
RUN ./configure --prefix=/install
RUN make
RUN make install

FROM ubuntu:20.04 as package
COPY --from=builder /install /install
